# Generated by Django 4.1.2 on 2022-11-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_address_alter_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mellicode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کدملی'),
        ),
    ]
