# Generated by Django 4.1.2 on 2022-11-07 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reqtaxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_addr', models.CharField(max_length=200, verbose_name='آدرس مبدا')),
                ('dest_addr', models.CharField(max_length=200, verbose_name='ادرس مقصد')),
                ('search_for_taxi', models.BooleanField(default=True, verbose_name='درحال جست و جو برای تاکسی')),
                ('achieve_dest', models.BooleanField(default=False, verbose_name='رسیده به مقصد')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('travel_costs', models.IntegerField(verbose_name='هزینه سفر')),
                ('type_travel', models.CharField(choices=[('Delivery', 'پیک'), ('Taxi', 'تاکسی'), ('Truck', 'کامیون'), ('Pickup_truck', 'وانت')], help_text='Insert type of travel', max_length=15, verbose_name='نوع سفر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
