# Generated by Django 4.1.2 on 2022-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqtaxi',
            name='type_travel',
            field=models.CharField(choices=[('Delivery', 'delivery'), ('Taxi', 'taxi'), ('Truck', 'truck'), ('Pickup_truck', 'pickup_truck')], help_text='Insert type of travel', max_length=15),
        ),
    ]
