# Generated by Django 4.1.2 on 2022-11-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqtaxi',
            name='achieve_dest',
            field=models.BooleanField(default=False, verbose_name='رسیده به مقصد'),
        ),
        migrations.AlterField(
            model_name='reqtaxi',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='reqtaxi',
            name='dest_addr',
            field=models.CharField(max_length=200, verbose_name='ادرس مقصد'),
        ),
        migrations.AlterField(
            model_name='reqtaxi',
            name='orig_addr',
            field=models.CharField(max_length=200, verbose_name='آدرس مبدا'),
        ),
        migrations.AlterField(
            model_name='reqtaxi',
            name='search_for_taxi',
            field=models.BooleanField(default=True, verbose_name='درحال جست و جو برای تاکسی'),
        ),
        migrations.AlterField(
            model_name='reqtaxi',
            name='travel_costs',
            field=models.IntegerField(verbose_name='هزینه سفر'),
        ),
        migrations.AlterField(
            model_name='reqtaxi',
            name='type_travel',
            field=models.CharField(choices=[('Delivery', 'delivery'), ('Taxi', 'taxi'), ('Truck', 'truck'), ('Pickup_truck', 'pickup_truck')], help_text='Insert type of travel', max_length=15, verbose_name='نوع سفر'),
        ),
    ]
