# Generated by Django 4.1.2 on 2022-11-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reqtaxi_achieve_dest_alter_reqtaxi_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqtaxi',
            name='type_travel',
            field=models.CharField(choices=[('Delivery', 'پیک'), ('Taxi', 'تاکسی'), ('Truck', 'کامیون'), ('Pickup_truck', 'وانت')], help_text='Insert type of travel', max_length=15, verbose_name='نوع سفر'),
        ),
    ]
