# Generated by Django 4.1.2 on 2022-11-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_traveladdress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveladdress',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
