# Generated by Django 4.1.2 on 2022-11-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_traveladdress_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveladdress',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
