# Generated by Django 4.1.2 on 2022-11-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_traveladdress_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveladdress',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='نام محل'),
        ),
    ]
