# Generated by Django 4.1.2 on 2022-12-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver_job',
            options={'verbose_name': 'اطلاعات سفر ', 'verbose_name_plural': 'سفر های رانندگان  '},
        ),
    ]
